yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_post'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(
        url='/static/img/fav/favicon.ico')
    ),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


def delete_user():
    User.objects.get_or_create(username='anonymous')[0]


class Group(models.Model):
    """Описание модели группы"""
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    """
    Post описывает модель БД для работы с постами.
    author:
        связь с таблицей пользователей.
        При удалении выполенении функции выставления anonymous в поле
        пользователя. Реализовал, для тестирования функционала действий при
        удалении.
    group:
        связь с таблицей групп.
        При удалении группы, в постах просто ставим NULL
    """
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET(delete_user),
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': ('Текст поста'),
            'group': ('Группа поста')
        }

        help_texts = {
            'text': ('Введите текст поста'),
            'group': ('Выберите группу поста (опционально)')
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth import get_user_model


User = get_user_model()


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required

from .models import Group, Post, User
from .forms import PostForm

POSTS_COUNT = 10
User = get_user_model()


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    paginator = Paginator(posts, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    """
    Функция для отображения групп.
    Фильтр только опубликованых постов.
    """
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_number = request.GET.get('page')
    paginator = Paginator(posts, POSTS_COUNT)
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    post_count = post_list.count()
    paginator = Paginator(post_list, POSTS_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'username': user,
        'page_obj': page_obj,
        'post_count': post_count,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    post_count = Post.objects.filter(author=author).count()

    context = {
        'post': post,
        'post_count': post_count,
        'author': author,
    }
    return render(request, template, context)


# Проверяем, авторизован ли пользователь
@login_required
def post_edit(request, post_id):
    # используем тот же шаблон, что и для создания поста
    template = 'posts/create_post.html'
    # получаем модель для редактирования по номеру поста
    post = get_object_or_404(Post, pk=post_id)
    # проверим, что редактировать будет автор поста
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    # создаем форму, с данными поста для редактирования
    # с проверкой запроса POST
    form = PostForm(request.POST or None, instance=post)
    # проверка формы
    if form.is_valid():
        # если проверка формы прошла, сохраняем
        # и делаем редирект на информацию о постах
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user.username)
    context = {
        'form': form,
    }
    return render(request, template, context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
  <p>Обо мне.</p>
  <p>Напишу когда-нибудь =^.^=</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}


<!DOCTYPE html> 
<html lang="ru">          
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Yatube!{% endblock %}</title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright<span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href={% url 'posts:index' %}>
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link " 
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        {% comment %} <li class="nav-item"> 
          <a class="nav-link link-light" href="<!--  -->">Изменить пароль</a>
        </li>
        {% endcomment %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% endif %}
        {% if user.is_authenticated == False %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        {% endif %}
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endwith %} 
      </ul>
    </div>
</nav>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Добавить запись
  {% endif %}
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post" action="">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger" >*</span>
                </label>
                {{form.text}}
                <small id="id_text-help" class="form-text text-muted">
                  Текст новой записи
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  Укажите группу для поста
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}Записи сообщества{{ group.title }}{% endblock %}

{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <h1>
        {{ group.title }}
        </h1>
        <p>
          {{ group.description }}
        </p>
          {% for post in posts %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>{{ post.text }}</p>
            {% if not forloop.last %}<hr>{% endif %}
          </article>
          {% endfor %}
          <div>
            <a href={% url 'posts:index' %} class="btn btn-primary">На главную</a>
          </div>         
      </div>  
    </main>  
  </body>
{% endblock %} 

yatube/templates/posts/includes/paginator.html
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
          </li>
        {% endif %}
        {% for page_number in page_obj.paginator.page_range %}
            {% if page_obj.number == page_number %}
              <li class="page-item active">
                <span class="page-link">{{ page_number }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
          </li>
        {% endif %}    
      </ul>
    </nav>
    {% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <body>
    <main> 
      <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
          {% for post in page_obj %}
            <article class="card-body">
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>
              <p>{{ post.text }}</p>
              {% if user.is_authenticated %}
                <a href={% url 'posts:post_edit' post.id %} class="btn btn-primary">Редактировать пост</a>
              {% endif %}
              {% if post.group %}
                <a href={% url 'posts:group_post' post.group.slug %} class="btn btn-primary">Bсе записи группы</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
            </article>
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
      </div>
    </main>      
  </body>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост: {{text_title}} {% endblock %}
{% block content %}
<body>
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Дата публикации:
            <span>{{ post.pub_date|date:"d E Y" }}</span>
          </li>
          {% if group.slug %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:posts_group' post.group %}">
              все записи группы
            </a>
            {% endif %}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Автор:
            <span>{{ post.author }}</span>
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: 
             <span>{{ post_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          {{ text }}
        </p>
      </article>
    </div>
  </main>
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Все записи пользователя {{ username }}{% endblock %}

{% block content %}
<h3>Всего постов: {{ post_count }}</h3>
{% for post in page_obj %}

<article>
  <ul>
    <li>
      Автор:
      {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
</article>
{% if post.group %}
  <a href="{% url 'posts:group_post' post.group.slug %}">все записи группы</a>
{% endif %}
{% if not forloop.last %}
  <hr>
{% endif %}

{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            {% comment %} <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a> {% endcomment %}
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}